INSERT INTO clients (clientName, clientEmail, clientPhone, clientAvailability, clientAbout) VALUES ("Dj Qualls", "Quallstothewall@gmail.com", "http://madeinatlantis.com/biography/248768f40.jpg", "evening", "GET HUGE!");
INSERT INTO clients (clientName, clientEmail, clientPhone, clientAvailability, clientAbout) VALUES ("Peter Griffen", "petey@hotmail.com", "https://s3.amazonaws.com/pq-imgs/images/quizzes/family-guy-Peter_G-2389.jpg", "evening", "Only doing so I can have more beer.");
INSERT INTO clients (clientName, clientEmail, clientPhone, clientAvailability, clientAbout) VALUES ("Sherman Klump", "sheralotofman@gmail.com", "http://tr.web.img4.acsta.net/r_1920_1080/pictures/14/04/14/13/45/342144.jpg", "evening", "Rather be doing science.");
INSERT INTO clients (clientName, clientEmail, clientPhone, clientAvailability, clientAbout) VALUES ("Matt Damon", "whataDamon@yahoo.com", "http://www.dareandconquer.com/wp-content/uploads/2015/09/losing-fat-matt-damon-informant.jpg", "afternoon", "No more muffin top.");
INSERT INTO clients (clientName, clientEmail, clientPhone, clientAvailability, clientAbout) VALUES ("SpongeBob", "lilSpongy@hotmail.com", "https://i.redd.it/nqly77a38jsy.png", "afternoon", "Bigger legs");
INSERT INTO clients (clientName, clientEmail, clientPhone, clientAvailability, clientAbout) VALUES ("Ned Schneebly", "needaned@msn.com", "https://thumbs.dreamstime.com/z/jeune-homme-faible-86361162.jpg", "afternoon", "Exercise mind and body.");
INSERT INTO clients (clientName, clientEmail, clientPhone, clientAvailability, clientAbout) VALUES ("Ron Howard", "howeird@gmail.com", "https://static.tvtropes.org/pmwiki/pub/images/ron-howard-picture_7816.jpg", "morning", "I need a hobby.");
INSERT INTO clients (clientName, clientEmail, clientPhone, clientAvailability, clientAbout) VALUES ("Noel Fielding", "NoelPatrol@noel.com", "https://cdn.images.express.co.uk/img/dynamic/79/590x/526179_1.jpg", "morning", "Don't ask!");
INSERT INTO clients (clientName, clientEmail, clientPhone, clientAvailability, clientAbout) VALUES ("Shia Labeouf", "notveryshia@msn.com", "http://www.showbiz411.com/wp-content/uploads/2014/02/ShiaLabeouf.jpg", "morning", "JUST DO IT!");



INSERT INTO trainers (trainerName, trainerEmail, trainerPhone, trainerAvailability, trainerAbout) VALUES ("Arnie", "getlifting@gmail.com", "https://assets3.thrillist.com/v1/image/1478364/size/tmg-article_main_wide_2x.jpg", "evening", "Bigger muscles are better muscles");
INSERT INTO trainers (trainerName, trainerEmail, trainerPhone, trainerAvailability, trainerAbout) VALUES ("Hulk", "hulksmash@msn.com", "https://cdn3.whatculture.com/images/2017/07/f35a22604066078f-600x400.jpg", "evening", "UGH!");
INSERT INTO trainers (trainerName, trainerEmail, trainerPhone, trainerAvailability, trainerAbout) VALUES ("The Mountain", "MountainTime@aol.com", "https://uproxx.files.wordpress.com/2017/08/got_the_mountain.jpg", "evening", "Pick that up and put it down!");
INSERT INTO trainers (trainerName, trainerEmail, trainerPhone, trainerAvailability, trainerAbout) VALUES ("Vlad", "niceBis@gmail.com", "https://cdni.rt.com/files/2017.11/article/5a088a24fc7e9302548b4568.jpg", "afternoon", "No they are real!");
INSERT INTO trainers (trainerName, trainerEmail, trainerPhone, trainerAvailability, trainerAbout) VALUES ("Glen", "glenisaten@gmail.com", "https://d28hgpri8am2if.cloudfront.net/author_images/7945/jeffry-s-life-72762558.jpg", "afternoon", "Be Confident");
INSERT INTO trainers (trainerName, trainerEmail, trainerPhone, trainerAvailability, trainerAbout) VALUES ("Little John", "robinsbud@gmail.com", "https://photos1.blogger.com/blogger/2088/2881/1600/RobinHood-PrinceOfThieves_28.jpg", "afternoon", "No I wasn't in that movie");
INSERT INTO trainers (trainerName, trainerEmail, trainerPhone, trainerAvailability, trainerAbout) VALUES ("Big Don", "donalarm@aol.com", "http://mid-south-boxing.2299399.n4.nabble.com/file/n4654809/butterbean-10_display_image.jpg", "morning", "Get fired up!");
INSERT INTO trainers (trainerName, trainerEmail, trainerPhone, trainerAvailability, trainerAbout) VALUES ("Doodles", "oodlesofdoodles@msn.com", "https://vignette.wikia.nocookie.net/uncyclopedia/images/6/6f/Tyson-young.jpg", "morning", "Is it leg day yet?");
INSERT INTO trainers (trainerName, trainerEmail, trainerPhone, trainerAvailability, trainerAbout) VALUES ("Brian", "Brian@gmail.com", "https://www.gewoonvoorhem.nl/app/uploads/fly-images/35317/mcgregor-gewoonvoorhem--1000x750-c.jpg", "morning", "Don't know what to put");
